# Generated by Django 5.2.15 on 2026-06-26 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_region_role_champion_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
