# Generated by Django 5.2.15 on 2026-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_champion_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='release_year',
        ),
        migrations.AddField(
            model_name='champion',
            name='release_date',
            field=models.DateField(default='2010-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='release_date',
            field=models.DateField(default='2010-01-01'),
            preserve_default=False,
        ),
    ]
