# Generated by Django 5.2.15 on 2026-06-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_champion_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='champions/'),
            preserve_default=False,
        ),
    ]
