# Generated by Django 5.2.15 on 2026-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_champion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='champions/'),
        ),
    ]
