# Generated by Django 5.2.15 on 2026-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_champion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image_position',
            field=models.CharField(default='center', max_length=50),
        ),
    ]
