# Generated by Django 5.2.15 on 2026-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_champion_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roles/'),
        ),
    ]
