# Generated by Django 5.2.15 on 2026-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_role_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='image_position',
            field=models.CharField(default='center center', max_length=50),
        ),
    ]
