# Generated by Django 5.2.15 on 2026-06-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_champion_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['name']},
        ),
    ]
