# Generated by Django 5.2.15 on 2026-07-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_champion_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skin',
        ),
    ]
