# Generated by Django 5.2.15 on 2026-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_delete_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='image_position',
            field=models.CharField(blank=True, default='center center', max_length=50),
        ),
    ]
